# Generated by Django 4.1.12 on 2023-10-28 04:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True, max_length=1500, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(default=datetime.datetime(2023, 10, 28, 10, 23, 12, 268454))),
                ('img', models.ImageField(blank=True, null=True, upload_to='quizzes/')),
                ('number_of_questions', models.IntegerField(default=0)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='question_img/')),
                ('text', models.CharField(max_length=300)),
                ('choice_a', models.CharField(max_length=50)),
                ('choice_b', models.CharField(max_length=50)),
                ('choice_c', models.CharField(blank=True, max_length=50, null=True)),
                ('choice_d', models.CharField(blank=True, max_length=50, null=True)),
                ('correct_choice', models.CharField(choices=[('A', 'Choice A'), ('B', 'Choice B'), ('C', 'Choice C'), ('D', 'Choice D')], max_length=1)),
                ('time', models.IntegerField(default=20)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(related_name='group_user', to=settings.AUTH_USER_MODEL)),
                ('quizzes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_quiz', to='quiz.quiz')),
            ],
        ),
    ]
