# Generated by Django 4.2.6 on 2023-10-26 16:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quiz_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='quizzes',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 22, 40, 46, 699401)),
        ),
        migrations.AddField(
            model_name='group',
            name='quizzes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_quiz', to='quiz.quiz'),
            preserve_default=False,
        ),
    ]
