# Generated by Django 4.1.12 on 2023-10-27 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_group_quizzes_alter_quiz_update_group_quizzes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 22, 32, 17, 350190)),
        ),
    ]
