# Generated by Django 4.1.12 on 2023-10-27 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_quiz_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 22, 34, 36, 339514)),
        ),
    ]
