# Generated by Django 4.1.12 on 2023-10-28 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_question_correct_choice_alter_quiz_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 19, 39, 12, 753217)),
        ),
    ]
