# Generated by Django 4.1.12 on 2023-10-28 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_quiz_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('pendeng', 'pendeng'), ('in progress', 'in progress'), ('complete', 'complete')], default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 20, 0, 36, 224009)),
        ),
    ]
