# Generated by Django 4.1.12 on 2023-11-03 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_alter_quiz_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 14, 52, 5, 827404)),
        ),
    ]
