# Generated by Django 4.1.12 on 2023-11-04 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_room_password_room_private_alter_quiz_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 13, 47, 53, 183644)),
        ),
        migrations.AlterField(
            model_name='room',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
