# Generated by Django 4.1.12 on 2023-10-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quiz_update'),
        ('user', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rooms',
        ),
        migrations.AddField(
            model_name='profile',
            name='rooms',
            field=models.ManyToManyField(related_name='memberships', to='quiz.room'),
        ),
    ]
