# Generated by Django 4.1.12 on 2023-10-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_user_remove_profile_rooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rooms',
        ),
    ]
