# Generated by Django 4.1.12 on 2023-11-09 15:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True, max_length=1500, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(default=datetime.datetime(2023, 11, 9, 21, 52, 38, 777485))),
                ('img', models.ImageField(blank=True, null=True, upload_to='quizzes/')),
                ('question', models.IntegerField(default=0)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pendeng', 'pendeng'), ('in progress', 'in progress'), ('complete', 'complete')], max_length=150)),
                ('private', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('members', models.ManyToManyField(related_name='rooms', to=settings.AUTH_USER_MODEL)),
                ('quizzes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_quiz', to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='question_img/')),
                ('text', models.CharField(max_length=300)),
                ('choice_a', models.CharField(max_length=50)),
                ('choice_b', models.CharField(max_length=50)),
                ('choice_c', models.CharField(blank=True, max_length=50, null=True)),
                ('choice_d', models.CharField(blank=True, max_length=50, null=True)),
                ('correct_choice', models.IntegerField(choices=[(1, 'Choice A'), (2, 'Choice B'), (3, 'Choice C'), (4, 'Choice D')])),
                ('time', models.IntegerField(default=20)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='quiz.quiz')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
