# Generated by Django 4.1.12 on 2023-10-30 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_room_question_room_status_alter_quiz_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 20, 13, 13, 607696)),
        ),
    ]
