# Generated by Django 4.1.12 on 2023-10-30 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_user'),
        ('quiz', '0014_remove_quiz_number_of_questions_alter_quiz_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 0, 14, 2, 452633)),
        ),
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(related_name='rooms', to='user.profile'),
        ),
    ]
