# Generated by Django 4.1.12 on 2023-11-03 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_quiz_update_alter_room_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 14, 51, 57, 447756)),
        ),
    ]
