# Generated by Django 4.1.12 on 2023-11-04 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_alter_quiz_update_alter_room_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 14, 5, 5, 929480)),
        ),
    ]
