# Generated by Django 4.1.12 on 2023-10-28 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_remove_profile_group_profile_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ManyToManyField(related_name='user_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
