# Generated by Django 4.2.6 on 2023-10-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_number_of_completed_games_profile_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background',
        ),
    ]
