# Generated by Django 4.1.12 on 2023-11-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
